force-app/main/default/objects/Case/fields/Desired_inspection_start__c.field-meta.xml
<CustomField>
    <fullName>Desired_inspection_start__c</fullName>
    <label>Desired inspection start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/ExperienceUrl__c.field-meta.xml
<CustomField>
    <fullName>ExperienceUrl__c</fullName>
    <formula>&apos;https://gmailcomiv-dev-ed.develop.my.site.com/s/case/&apos; + Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Experience Url</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Inspection_Types__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Types__c</fullName>
    <label>Inspection Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Materials quality inspection</fullName>
            </value>
            <value>
                <fullName>Materials storage inspection</fullName>
            </value>
            <value>
                <fullName>Equipment inspection</fullName>
            </value>
            <value>
                <fullName>Manufacture process inspection</fullName>
            </value>
            <value>
                <fullName>Outcome count inspection</fullName>
            </value>
            <value>
                <fullName>Outcome quality inspection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Manufacture__c.field-meta.xml
<CustomField>
    <fullName>Manufacture__c</fullName>
    <label>Manufacture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>South 1</fullName>
            </value>
            <value>
                <fullName>South 2</fullName>
            </value>
            <value>
                <fullName>South 3</fullName>
            </value>
            <value>
                <fullName>North 1</fullName>
            </value>
            <value>
                <fullName>North-west 1</fullName>
            </value>
            <value>
                <fullName>Western 1</fullName>
            </value>
            <value>
                <fullName>East 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andalusia</fullName>
            </value>
            <value>
                <fullName>Aragon</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Balearic Islands</fullName>
            </value>
            <value>
                <fullName>Basque Country</fullName>
            </value>
            <value>
                <fullName>Canary Islands</fullName>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castile and Leon</fullName>
            </value>
            <value>
                <fullName>Castilla–La Mancha</fullName>
            </value>
            <value>
                <fullName>Catalonia</fullName>
            </value>
            <value>
                <fullName>Extremadura</fullName>
            </value>
            <value>
                <fullName>Galicia</fullName>
            </value>
            <value>
                <fullName>La Rioja</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
            <value>
                <fullName>Murcia</fullName>
            </value>
            <value>
                <fullName>Navarre</fullName>
            </value>
            <value>
                <fullName>Valencia</fullName>
            </value>
            <value>
                <fullName>East</fullName>
                <isActive>false</isActive>
                <label>East</label>
            </value>
            <value>
                <fullName>North</fullName>
                <isActive>false</isActive>
                <label>North</label>
            </value>
            <value>
                <fullName>South</fullName>
                <isActive>false</isActive>
                <label>South</label>
            </value>
            <value>
                <fullName>West</fullName>
                <isActive>false</isActive>
                <label>West</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Generators_support.recordType-meta.xml
<RecordType>
    <fullName>Generators_support</fullName>
    <active>true</active>
    <businessProcess>Generatordss support process</businessProcess>
    <label>Generators support</label>
</RecordType>

force-app/main/default/classes/MGCasePageController.cls
public with sharing class MGCasePageController {

    @AuraEnabled
    public static List<Case> getCases(String[] statuses) {
        String soql = 'SELECT Id, CaseNumber, Subject, CreatedDate, Status, Region__c, Manufacture__c, Inspection_Types__c, Desired_inspection_start__c, ExperienceUrl__c ' + 
            'FROM Case WHERE RecordType.DeveloperName = \'Generators_support\'';
        
        if(statuses != null && !statuses.isEmpty()) {
            soql += ' AND Status IN :statuses';
        }

        return Database.query(soql);
    }
}